"""Generates the three machine/human-readable report formats Milestone 10
requires — Markdown, CSV, and raw JSON — always from real
`ExperimentResult` records, never from hand-entered numbers.
"""

import csv
import io
import json
from collections.abc import Sequence

from research.core.schemas import ExperimentResult

CSV_FIELDS = [
    "experiment_id",
    "scenario_id",
    "configuration",
    "distance_km",
    "route_risk",
    "risk_reduction_percent",
    "distance_overhead_percent",
    "runtime_ms",
    "found",
]


def to_csv(results: Sequence[ExperimentResult]) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=CSV_FIELDS)
    writer.writeheader()
    for result in results:
        writer.writerow({field: getattr(result, field) for field in CSV_FIELDS})
    return buffer.getvalue()


def to_json(results: Sequence[ExperimentResult]) -> str:
    return json.dumps([result.model_dump(mode="json") for result in results], indent=2)


def _format_percent(value: float | None) -> str:
    return f"{value:.1f}" if value is not None else "n/a"


def to_markdown(results: Sequence[ExperimentResult], title: str) -> str:
    lines = [
        f"# {title}",
        "",
        "| Configuration | Scenario | Distance (km) | Risk | Risk reduction % | "
        "Distance overhead % | Runtime (ms) | Found |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for result in results:
        lines.append(
            f"| {result.configuration} | {result.scenario_id} | {result.distance_km:.3f} | "
            f"{result.route_risk:.3f} | {_format_percent(result.risk_reduction_percent)} | "
            f"{_format_percent(result.distance_overhead_percent)} | {result.runtime_ms:.3f} | "
            f"{result.found} |"
        )
    lines.append("")
    lines.append(
        "_Generated by `research/core/report.py` from measured `ExperimentResult` records — "
        "every value above comes from an actual routing/risk computation, never hand-entered._"
    )
    return "\n".join(lines)
