blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/orgs/sentinelai/discussions
    about: For usage questions and general discussion, please use GitHub Discussions instead of an issue.
