/**
 * The "research presentation rule": every piece of information in the UI
 * must be traceable to exactly one of these four categories, so a
 * responder never mistakes a model prediction or an LLM sentence for a
 * measured fact. Styled like `lib/risk-colors.ts` (code + label + color),
 * plus a `description` used as the badge's accessible/hover explanation.
 * See `docs/architecture/frontend.md`, "Data provenance labeling".
 *
 * One easy-to-get-wrong case: `IncidentBriefing.incident_severity`,
 * `.confidence`, and `.affected_structures` are NOT generated by the LLM —
 * `app/incident/severity.py` computes all three deterministically from
 * real `BuildingDamage`/`DamageSummary` data server-side, and silently
 * discards any LLM output that tries to set those keys. Only
 * `priority_area`/`route_summary`/`key_findings`/`limitations` are
 * genuine LLM (or deterministic-fallback-template) prose — those are
 * "generated"; the rest of `IncidentBriefing` is "calculated". See
 * `briefing-panel.tsx` for the exact per-field assignment.
 */

/**
 * **F3 adds a fifth category, `simulated`**, for data that is real
 * neither as measurement nor as inference — the demo resource pool
 * (`app.intelligence.demo_scenario`) reused by
 * `app.intelligence.analysis_adapter` because no real resource-ingestion
 * system exists yet. Deliberately distinct from the app-wide "Demo mode"
 * badge (`incident-status-bar.tsx`): a resource candidate can be
 * `simulated` even while the surrounding analysis (damage, search zones)
 * is real — see `intelligence-panel.tsx`, the one place both appear side
 * by side.
 */
export type ProvenanceCategory = "observed" | "predicted" | "calculated" | "generated" | "simulated";

interface ProvenanceStyle {
  code: string;
  label: string;
  description: string;
  className: string;
}

export const PROVENANCE_STYLE: Record<ProvenanceCategory, ProvenanceStyle> = {
  observed: {
    code: "OBS",
    label: "Observed",
    description: "Read directly from the uploaded file — not inferred.",
    className: "text-sky-400 border-sky-500/40 bg-sky-500/10",
  },
  predicted: {
    code: "PRED",
    label: "Predicted",
    description: "Output of the damage-classification model.",
    className: "text-violet-400 border-violet-500/40 bg-violet-500/10",
  },
  calculated: {
    code: "CALC",
    label: "Calculated",
    description: "Deterministically computed from other real data (a documented formula, not a model).",
    className: "text-emerald-400 border-emerald-500/40 bg-emerald-500/10",
  },
  generated: {
    code: "GEN",
    label: "AI-generated",
    description: "Written by the incident-briefing LLM (or its deterministic fallback) — a summary, not a measurement.",
    className: "text-amber-400 border-amber-500/40 bg-amber-500/10",
  },
  simulated: {
    code: "SIM",
    label: "Simulated",
    description: "A deterministic demo/placeholder entity — not real telemetry, even when the surrounding analysis is real.",
    className: "text-fuchsia-400 border-fuchsia-500/40 bg-fuchsia-500/10",
  },
};
